<?php
/**
 * @file
 * A module that can be used for custom hooks that are too small for their own module
 */

/**
 * Implements hook_form__alter().
 *
 * Uncomment this function to print out $form_id on form pages
 */
//function custom_functions_form_alter(&$form, $form_state, $form_id) {
//    drupal_set_message($form_id);
//}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * Changes 'submit' button label from 'Save' to 'Post results' for form ID 'match_node_form'
 */
function custom_functions_form_node_form_alter(&$form, $form_state, $form_id) {
   $form['actions']['submit']['#value'] = t('Post results');
   $form['field_player2']['und'][0]['target_id']['#title_display'] = 'invisible';
   $form['field_player4']['und'][0]['target_id']['#title_display'] = 'invisible';
}

function custom_functions_hybridauth_user_preinsert($account, $data) {
    $domains = 'acquia.com';

    if(isset($domains)) {

        $userEmailDomain = explode("@", $data["email"]);
        if($userEmailDomain[1] != $domains) {
            module_load_include("inc", "hybridauth", "hybridauth.pages");
            drupal_set_message("Only users with valid emails are allowed to register", "error");
            session_destroy();
            _hybridauth_window_close();
        }
    }
}


